"""The paper-to-code map: every equation of [WU26] and every decision of ours, to the function that
implements it and the test that checks it.

Code cites an equation with one tag form, `[WU26 eq. 28]`, `[WU26 eqs. 21-23, 27]` or
`[WU26 Alg. 1]`, and one of our decisions with `[D9]` or `[E13]`, in the docstring or a comment of
the function that implements it (`schema.WU26_EQUATIONS` and `schema.DECISIONS` list what exists). A
test cites what it checks the same way, or names it (`test_wu26_eq28_...`). This tool walks the
package and the tests and writes three generated pieces of the docs:

    docs/reference/DECISIONS.md        the decisions, paper or ours, where each is implemented and tested
    docs/reference/FORMULAS.md         the "[WU26] equations to code" section
    docs/reference/CONCEPTS_TO_CODE.md the module table

    python tools/equation_map.py            # write them
    python tools/equation_map.py --check    # the gate: stale docs, unknown or malformed tags, and an
                                            # equation with no implementing function or no test fail
"""

from __future__ import annotations

import argparse
import ast
import os
import re
import sys
from collections import defaultdict
from collections.abc import Iterable

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "fdia_graph")
TESTS = os.path.join(ROOT, "tests")
sys.path.insert(0, os.path.join(ROOT, "src"))

from fdia_graph.schema import DECISIONS, WU26_EQUATIONS  # noqa: E402

TAG = re.compile(r"\[WU26 (?:eqs?\. ([0-9][0-9 ,\-]*)|(Alg\. 1))\]")
DECISION = re.compile(r"\[([DE](?:1[0-9]|[1-9]))\]")
MALFORMED = re.compile(r"\[WU26,")  # the old "[WU26, eq. 12]" form
TEST_NAME = re.compile(r"test_wu26_eqs?(\d+)(?:_(\d+))?")
SKIP = {os.path.join(SRC, "schema.py")}  # the registries: their examples are not citations

DOCS = os.path.join(ROOT, "docs", "reference")
FORMULAS = os.path.join(DOCS, "FORMULAS.md")
CONCEPTS = os.path.join(DOCS, "CONCEPTS_TO_CODE.md")
DECISIONS_MD = os.path.join(DOCS, "DECISIONS.md")
BEGIN, END = "<!-- equation-map: generated by tools/equation_map.py -->", "<!-- /equation-map -->"
MBEGIN, MEND = "<!-- module-table: generated by tools/equation_map.py -->", "<!-- /module-table -->"


def numbers(spec: str) -> list[str]:
    """The equation numbers a tag lists: "21-23, 27" -> ["21", "22", "23", "27"]."""
    out: list[str] = []
    for part in (p.strip() for p in spec.split(",") if p.strip()):
        lo, _, hi = part.partition("-")
        out += [str(n) for n in range(int(lo), int(hi or lo) + 1)]
    return out


def _owners(tree: ast.Module, module: str) -> list[tuple[int, int, str]]:
    """(first line, last line, qualified name) of every function and class, outer before inner."""
    out: list[tuple[int, int, str]] = []

    def walk(node: ast.AST, prefix: str) -> None:
        for child in ast.iter_child_nodes(node):
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                name = f"{prefix}.{child.name}"
                out.append((child.lineno, child.end_lineno or child.lineno, name))
                walk(child, name)

    walk(tree, module)
    return out


def _owner(owners: list[tuple[int, int, str]], line: int, module: str) -> str:
    """The innermost function or class holding `line`, else the module."""
    inside = [(a, n) for a, b, n in owners if a <= line <= b]
    return max(inside)[1] if inside else module


def _files(top: str) -> Iterable[str]:
    for d, _, names in os.walk(top):
        if "__pycache__" in d:
            continue
        for n in sorted(names):
            if n.endswith(".py") and os.path.join(d, n) not in SKIP:
                yield os.path.join(d, n)


def _module(path: str) -> str:
    rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
    mod = rel[len("src/") : -len(".py")] if rel.startswith("src/") else rel[: -len(".py")]
    mod = mod.replace("/", ".")
    return mod[: -len(".__init__")] if mod.endswith(".__init__") else mod


class Citations:
    """Who cites what: equation or decision -> implementing names, and -> tests; plus the problems."""

    def __init__(self) -> None:
        self.code: dict[str, set[str]] = defaultdict(set)
        self.tests: dict[str, set[str]] = defaultdict(set)
        self.problems: list[str] = []

    def add(self, key: str, owner: str, is_test: bool, where: str) -> None:
        if key not in WU26_EQUATIONS and key not in DECISIONS:
            self.problems.append(f"{where}: unknown citation {key!r}")
            return
        (self.tests if is_test else self.code)[key].add(owner)

    def scan(self, path: str) -> None:
        text = open(path, encoding="utf-8").read()
        module = _module(path)
        owners = _owners(ast.parse(text), module)
        is_test = path.startswith(TESTS)
        for i, line in enumerate(text.splitlines(), 1):
            where, owner = f"{os.path.relpath(path, ROOT)}:{i}", _owner(owners, i, module)
            if MALFORMED.search(line):
                self.problems.append(f"{where}: write [WU26 eq. N], not [WU26, ...]")
            for m in TAG.finditer(line):
                for key in [m.group(2)] if m.group(2) else numbers(m.group(1)):
                    self.add(key, owner, is_test, where)
            for m in DECISION.finditer(line):
                self.add(m.group(1), owner, is_test, where)
        if is_test:
            for _, _, name in owners:
                for m in TEST_NAME.finditer(name.rsplit(".", 1)[-1]):
                    for key in numbers(f"{m.group(1)}-{m.group(2)}" if m.group(2) else m.group(1)):
                        self.add(key, name, True, os.path.relpath(path, ROOT))

    def missing(self) -> list[str]:
        """Every equation the package lists with no implementing function or no test."""
        out = []
        for key in WU26_EQUATIONS:
            gaps = [
                what for what, have in (("function", self.code), ("test", self.tests)) if not have.get(key)
            ]
            if gaps:
                out.append(f"[WU26 {_label(key)}] has no {' and no '.join(gaps)}")
        return out


def _label(key: str) -> str:
    return key if key.startswith("Alg") else f"eq. {key}"


def _names(names: Iterable[str]) -> str:
    shown = sorted(n.removeprefix("fdia_graph.") for n in names)
    return "<br>".join(f"`{n}`" for n in shown) if shown else "none"


def equations_section(c: Citations) -> str:
    rows = [
        "| [WU26] | states | implemented in | tested by |",
        "|---|---|---|---|",
    ]
    for key, says in WU26_EQUATIONS.items():
        rows.append(f"| {_label(key)} | {says} | {_names(c.code[key])} | {_names(c.tests[key])} |")
    return "\n".join(rows)


def decisions_doc(c: Citations) -> str:
    head = (
        "# Decisions: how the package reads [WU26]\n\n"
        "Generated by `tools/equation_map.py` from `schema.DECISIONS` and the `[D9]` / `[E13]` tags in the\n"
        'code; edit those, not this file. "paper" is the paper\'s own reading, "ours" a choice it leaves\n'
        "open. The plans hold the reasoning behind each.\n\n"
        "| id | rule | paper or ours | plan | implemented in | tested by |\n"
        "|---|---|---|---|---|---|\n"
    )
    rows = [
        f"| {k} | {d.rule} | {d.source} | {d.plan} | {_names(c.code[k])} | {_names(c.tests[k])} |"
        for k, d in DECISIONS.items()
    ]
    return head + "\n".join(rows) + "\n"


def module_table() -> str:
    """Every module of the package with the first line of its docstring."""
    rows = ["| module | what it holds |", "|---|---|"]
    for path in _files(SRC):
        doc = ast.get_docstring(ast.parse(open(path, encoding="utf-8").read())) or ""
        first = " ".join(doc.split("\n\n", 1)[0].split()) if doc else ""
        rows.append(
            f"| `{_module(path).removeprefix('fdia_graph.') or 'fdia_graph'}` | {first.replace('|', '/')} |"
        )
    return "\n".join(rows)


def _splice(text: str, begin: str, end: str, body: str) -> str:
    """`text` with the block between the markers replaced by `body` (appended when absent)."""
    block = f"{begin}\n{body}\n{end}"
    if begin in text and end in text:
        a, b = text.index(begin), text.index(end) + len(end)
        return text[:a] + block + text[b:]
    return text.rstrip("\n") + "\n\n" + block + "\n"


def rendered(c: Citations) -> dict[str, str]:
    formulas = open(FORMULAS, encoding="utf-8").read()
    concepts = open(CONCEPTS, encoding="utf-8").read()
    return {
        DECISIONS_MD: decisions_doc(c),
        FORMULAS: _splice(formulas, BEGIN, END, equations_section(c)),
        CONCEPTS: _splice(concepts, MBEGIN, MEND, module_table()),
    }


def collect() -> Citations:
    c = Citations()
    for path in [*_files(SRC), *_files(TESTS)]:
        c.scan(path)
    return c


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument(
        "--check", action="store_true", help="fail on stale docs, bad tags or an untested equation"
    )
    args = ap.parse_args()
    c = collect()
    docs = rendered(c)
    problems = c.problems + c.missing()
    if args.check:
        stale = [
            os.path.relpath(p, ROOT)
            for p, body in docs.items()
            if not os.path.exists(p) or open(p, encoding="utf-8").read() != body
        ]
        problems += [f"{p} is stale: run python tools/equation_map.py" for p in stale]
        for p in problems:
            print(p)
        return 1 if problems else 0
    for path, body in docs.items():
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(body)
    for p in problems:
        print(p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
